# Generated by Django 4.0.3 on 2022-11-09 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='标题')),
                ('keyword', models.CharField(max_length=16, verbose_name='关键字')),
                ('source', models.CharField(max_length=16, verbose_name='来源')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('pro_status', models.CharField(default='N', max_length=1, verbose_name='发布状态')),
            ],
            options={
                'verbose_name': '新闻列表',
                'verbose_name_plural': '新闻列表',
            },
        ),
    ]
