# Generated by Django 4.0.3 on 2022-11-22 03:35

import ckeditor_uploader.fields
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='111'),
        ),
        migrations.AlterField(
            model_name='user',
            name='head_img',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='path/to/', variations={}, verbose_name='url'),
        ),
    ]
