# Generated by Django 4.0.3 on 2022-11-22 06:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_alter_solutionmodel_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
